package com.fambam.api.model;
// Generated 23/08/2017 7:07:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelationshipId generated by hbm2java
 */
@Embeddable
public class RelationshipId implements java.io.Serializable {

	private static final long serialVersionUID = -7848496298107373333L;
	private long userFrom;
	private long userTo;

	public RelationshipId() {
	}

	public RelationshipId(long userFrom, long userTo) {
		this.userFrom = userFrom;
		this.userTo = userTo;
	}

	@Column(name = "user_from", nullable = false)
	public long getUserFrom() {
		return this.userFrom;
	}

	public void setUserFrom(long userFrom) {
		this.userFrom = userFrom;
	}

	@Column(name = "user_to", nullable = false)
	public long getUserTo() {
		return this.userTo;
	}

	public void setUserTo(long userTo) {
		this.userTo = userTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelationshipId))
			return false;
		RelationshipId castOther = (RelationshipId) other;

		return (this.getUserFrom() == castOther.getUserFrom()) && (this.getUserTo() == castOther.getUserTo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserFrom();
		result = 37 * result + (int) this.getUserTo();
		return result;
	}

}
